import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNavbar from "@/components/SideNavbar";
import ReactQueryProvider from "@/hooks/queryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <div className="flex">
            <SideNavbar/>
            <main className="flex-1">
            <div className="flex flex-col sm:border-r sm:border-zinc-700 min-h-screen">
              <div className="flex flex-col pt-2 px-4 space-y-2 bg-zinc-100 flex-grow pb-4">
              <ReactQueryProvider>
                {children}
              </ReactQueryProvider>

              </div>
            </div>
          </main>
          </div>      
        </body>
    </html>
  );
}
